[platformio]
src_dir = .
include_dir = include
default_envs = esp32_audio_kit

[env]
build_flags =
  -std=gnu++17
  -Iinclude
build_unflags = -std=gnu++11

[env:native]
platform = native
build_src_filter =
  +<src/*.cpp>
  +<host/simulator.cpp>
  -<esp32/>
  -<tests/>

[env:esp32_audio_kit]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_src_filter =
  +<src/*.cpp>
  +<esp32/*.cpp>
  -<host/>
  -<tests/>
lib_deps =
  https://github.com/pschatzmann/arduino-audio-driver.git#f0704b2d82604b95db0748e832d6b72c5bd8bac4
  https://github.com/pschatzmann/arduino-audio-tools.git#5b646b99ef79f10734eb5c81ff99dbcd7a77b979

[env:esp32_audio_kit_capture]
extends = env:esp32_audio_kit
build_flags =
  ${env.build_flags}
  -DAUDIOCONTROL_ADC_CAPTURE

[env:esp32_audio_kit_capture_output]
extends = env:esp32_audio_kit
build_flags =
  ${env.build_flags}
  -DAUDIOCONTROL_ADC_CAPTURE
  -DAUDIOCONTROL_CAPTURE_OUTPUT

[env:esp32_audio_kit_capture_input_only]
extends = env:esp32_audio_kit
build_flags =
  ${env.build_flags}
  -DAUDIOCONTROL_ADC_CAPTURE
  -DAUDIOCONTROL_CAPTURE_INPUT_ONLY

[env:esp32_audio_kit_capture_ble]
extends = env:esp32_audio_kit
build_flags =
  ${env.build_flags}
  -DAUDIOCONTROL_ADC_CAPTURE
  -DAUDIOCONTROL_CAPTURE_ENABLE_BLE
